### PR TITLE
Add an I2CBus to the available buses

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
It handles I2C backpacks as described in #12

### CODE REVIEW

**Comment by nils-van-zuijlen** [comment]
I tested it with the example on my Nucleo-F303RE with the LCD and backpack available on https://shop.mchobby.be/fr/afficheur-lcd-tft-oled/881-lcd-20x4-backpack-i2c-blanc-sur-bleu-3232100008816.html and it worked successfully.

**Comment by nils-van-zuijlen** [comment]
You may need to update `examples/stm32f30x-i2c/.cargo/config` and `examples/stm32f30x-i2c/memory.x` for your particular MCU.

**Comment by JohnDoneth** [comment]
Thanks for the PR! This is really cool! It didn't occur to me that we could implement the `Databus` trait for I2C. I bet we could implement SPI in the future as well... :thinking:. Anyway, is this ready to merge? I'll keep a note to update those configs on the stm example.

**Comment by nils-van-zuijlen** [comment]
It is ready to merge, unless you know a way to share an I2C peripheral between two structures, because you could want to connect two different screens to the same I2C bus.

**Comment by nils-van-zuijlen** [comment]
LGTM

**Comment by JohnDoneth** [comment]
Thanks for this! 👍

**Pull request merged**
